language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "O+g6SihchES42OVOdZ05Ok/2TAYT411thaUT2/JZOcr93xvYHs3oBjo1PxjPp4NW4kOt8VPsQtkr9ozC5FlveVu2vfewyG5dI7df06JQVhQk6Z8pGXFGoZH/1w+5NyWZoVDj/5A63KvzVCZz1ktfy2P/n2QkFfhkdSdyEsIm2xTbEA6CAdanYTi9vdkL7U4efRODGOp+JLFvDBWrmWUcn6Z5tCE3qSDwuyGNlLg2ZQEatO8feQmsKut9zMaJUiVEJgO3itQjTWaTMdUsKUwu1kEiCQUdZ3/vgSCRC7Vk5rEThKVqoP+S/qsWfu3J1aKJv4f8x/L1ApK7VoC43azpV+wmcZS0XaIqWAgX5BYX4+n5rceHuWWz5Y9C30Gn9PE8Am5OXoFLtjizkMsxlo9fKT0xvFDtFrCeGkHcd77fl//ZbXFeVVevvGSbKUMTu4PNT/5KGM+07LQ4Ysuy/KwTL/ESHarCIn5krwRJmqyWZOpMU/a9X36kW4f66yarDVYh7NJ6I64A9oZu2acEV5iGJpnfGDissyvTFoCOJLLK2e1ndk/pCscxaeBY/n/WQk72Rygbeys3R/fbV/SVN4qaeFBASZcIKP9ew/XXISSMmQupzp0Tr3BsT8b6+cAH672kvsQSwmvntvUlrCfXsZi4Rpw8zENIPUX5ZLsrcBDgBn0="
  matrix:
    # flo account
    # to generate yours : travis encrypt KONNECTOR_CONFIG=\'"`cat konnector-dev-config.json | tr -d '\n'`"\' -r konnectors/cozy-konnector-free-mobile
    - secure: "FUhnn/1/dJ7xxvrTb3OrHc/a+PiK8hcluEmLsm6jcMzgUbnMYd3GLncAnxaJ21n7/7MQrejNTOknPnZvx7B/CW/A63DTL1wIrEugWU7UQUA5gCG+bEeIQDlgsagFXFV8VKMc+NJ6QcyLrSY9PGxWQ4sVuoA4VrNlC9SQTWd2CoijaJ/B09cjVy3Q4CVHuh08he2blgZsRjdVuPhMGYJ70N/Iu5/DVe3ENqpjpU0emktT/3H+WNwX/dTzZbUnIrVb979NRiwaQxMTZ72T9OhQHLD9XU04Nxdqk1fpfSVIUrypfAzsRo2EHN1FBEMMZ/SYsWgBmo6mJclKfPQxuioJJC34jurkzs4S8Dqfj70CvtOmkR4Hsl8wTD/9f/0wq1FW/U9nrIm/ny9XFe1ukpCwEOTjV3oITfzrqZhAUHq/bPbGfgm7G5z1YPoP66iSnUE5UV7R1A/icT6l/QHpinmDUq4VIU4k0dd4evVIJR0xd4n0iDpm0g1v1ftpEJ0ocyf9Ks3r7urecDH3AZ8ponFp+VA6q6B0BoYJrZsWfznXCB2Z0x0naVn/FlOozsKOp9vH/qffJjYsn1AKDxOuO12bzXsefmQC8wChNct5sA4JgPFiUNLTVssZpho3Oj2C4ZPwVj86zvnAtMgc0PvIcvDTLfd3iv1LRQRLag1JfihKXLM="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
  - if [ $TRAVIS_SECURE_ENV_VARS = "true" ]; then yarn test; fi
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-free-mobile
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-free-mobile
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
