language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn standalone
- yarn build
after_success:
- test $TRAVIS_BRANCH = "master" && yarn run deploy:travis -- --branch=build
before_install:
- openssl aes-256-cbc -K $encrypted_6837e0a26d3c_key -iv $encrypted_6837e0a26d3c_iv
  -in konnector-dev-config.json.enc -out konnector-dev-config.json -d
