language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN>
    - secure: "O+g6SihchES42OVOdZ05Ok/2TAYT411thaUT2/JZOcr93xvYHs3oBjo1PxjPp4NW4kOt8VPsQtkr9ozC5FlveVu2vfewyG5dI7df06JQVhQk6Z8pGXFGoZH/1w+5NyWZoVDj/5A63KvzVCZz1ktfy2P/n2QkFfhkdSdyEsIm2xTbEA6CAdanYTi9vdkL7U4efRODGOp+JLFvDBWrmWUcn6Z5tCE3qSDwuyGNlLg2ZQEatO8feQmsKut9zMaJUiVEJgO3itQjTWaTMdUsKUwu1kEiCQUdZ3/vgSCRC7Vk5rEThKVqoP+S/qsWfu3J1aKJv4f8x/L1ApK7VoC43azpV+wmcZS0XaIqWAgX5BYX4+n5rceHuWWz5Y9C30Gn9PE8Am5OXoFLtjizkMsxlo9fKT0xvFDtFrCeGkHcd77fl//ZbXFeVVevvGSbKUMTu4PNT/5KGM+07LQ4Ysuy/KwTL/ESHarCIn5krwRJmqyWZOpMU/a9X36kW4f66yarDVYh7NJ6I64A9oZu2acEV5iGJpnfGDissyvTFoCOJLLK2e1ndk/pCscxaeBY/n/WQk72Rygbeys3R/fbV/SVN4qaeFBASZcIKP9ew/XXISSMmQupzp0Tr3BsT8b6+cAH672kvsQSwmvntvUlrCfXsZi4Rpw8zENIPUX5ZLsrcBDgBn0="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-free-mobile
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-free-mobile
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
